name: Publish Docker image
on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * FRI'
jobs:
  build:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/${{ github.repository_owner }}/pspdev-test:latest
        push: true
